name: Scrape latest data

on:
  schedule:
    - cron:  */5 * * * *
  workflow_dispatch:


jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Fetch latest data
      run: |-
        timestamp=$(date -u)
        echo "${timestamp}" > lastrun.txt
        echo "trying to pull something"
        https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/votes-remaining-page/national/president.json" | jq . > results.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
